//add dripping waterdrop

//interaction 1:
//creating a Div that is represented by variable dropBottom
var button = document.getElementById('p');
//make variable button listen to mouse hover, if mouse hovered over the button, then do function Drip
button.addEventListener('mouseover', Drip);


function Drip() {
  //loop that create 5 drops at the same time
  for (var i = 0; i < 5; i++) {
    //creating a Div that is represented by variable dropBottom
    var dropBottom = document.createElement('div');
    //add class 'cir-bottom'to this div
    dropBottom.className = 'cir-bottom';
    //get the element that has the id of 'container'
    var container = document.getElementById('container');
    //assign iteration number as id for variable dropTop
    dropBottom.id = i;
    //attach the cir-bottom div to the container div
    container.appendChild(dropBottom);
    //define that the vertical distance between each bottom part of the drop is 150px
    dropBottom.style.top = 530 + 150 * i + 'px';

    //creating a Div that is represented by variable dropTop
    var dropTop = document.createElement('div');
    //add class 'tri-top'to this div
    dropTop.classList.add('tri-top');
    //get the element that has the id of 'container'
    var container = document.getElementById('container');
    //assign iteration number as id for variable dropTop
    dropTop.id = i;
    //attach the tri-top div to the container div
    container.appendChild(dropTop);
    //define that the vertical distance between each top part of the drop is 150px
    dropTop.style.top = 500 + 150 * i + 'px';

    //for every even number of drops, the color of it will be blue
    if (i % 2 == 0 && i < 5) {
      dropBottom.style.backgroundColor = '#67aceb';
      dropTop.style.borderBottom = '50px solid #67aceb';
    }
  }
}



//interaction 2
//create a variable cirTop that is a element in html that has the id of 'cir-top'
var cirTop = document.getElementById('cir-top');
//make the element that is presente by variable cirTop listen to a click, if clicked, run function 'DownOrBlue'
cirTop.addEventListener('click', DownOrBlue);
//make the element that is presente by variable cirTop listen to when mouse is no longer on the top of the element, if so, run function 'BacktoPos'
cirTop.addEventListener('mouseout', BacktoPos);

//create a function called 'DownOrBlue'
function DownOrBlue() {
  //define variable random as a rounded integer of 10 times the number generated by Math.random
  var random = Math.floor(Math.random() * 10);
  //show the rounded integer of 10 times the number generated by Math.random in console
  console.log(Math.floor(Math.random() * 10));
  //if the generated number is smaller than 5 is true, change the background color of the element that is represented by variable cirTop
  //and add a class called 'glow' to the element that is represented by variable cirTop
  //otherwise, add a class called 'down to the element that is represented by variable cirTop'
  if (random < 5) {
    cirTop.style.backgroundColor = '#67aceb';
    cirTop.className = 'glow';
  } else {
    cirTop.className = 'down';
  }
}
//created a function that is called 'BacktoPos'
function BacktoPos() {
  //change the style of the element represented by cirTop to white
  cirTop.style.backgroundColor = 'white';
  //remove the class glow from the cirTop
  cirTop.classList.remove('glow');
}

//interaction 3
//define a variable called dripLeak, it represent a element that has the id of 'circle-in' in the html file
var dripLeak = document.getElementById('circle-in');

// create a function called OriWater
function OriWater() {
  //change the background color of the element that is represented by variable dripLeak to blue
  dripLeak.style.backgroundColor = '#67aceb';
}
//create a function called LateOri
function LateOri() {
  //make function OriWater run 1.3 seconds later then when the function is called
  setTimeout(OriWater, 1300);
}

//create a function called BlueLeak
function BlueLeak() {
  //define variable holeL as a div that is newly created in the html file by javascript
  var holeL = document.createElement('div');
  //add a class called 'rec-b-top' to the element that is represented by variable holeL
  holeL.className = 'rec-b-top';
  //variable container is a element that has the id of container in the html file
  var container = document.getElementById('container');
  //attach the variable holeL to the container, so it will show up
  container.appendChild(holeL);
  //change the background color of the element that is represented by variable holeL to blue
  holeL.style.backgroundColor = '#67aceb';
  //set the z index of the element that is represented by variable holeL to 99
  holeL.style.zIndex='99';
}

//create a function called blueLeakLate
function blueLeakLate() {
  //delays the function called BlueLeak to run 1.5 seconds later when called
  setTimeout(BlueLeak, 1500);
  //delays the function called Joke to run 3.5 seconds later when called
  setTimeout(Joke,3500);
}

//create a function called Joke
function Joke(){
  //an alert window pop up and shows text "Fix your Leakage? Pay me 100 bucks and click letter "R"!"
  alert('Fix your Leakage? Pay me 100 bucks and click letter "R"!');
}

//create a function called aLeakage
function aLeakage() {
  //define variable rand as the integer rounded from 8 times the number generated by Math.random
  var rand = Math.floor(Math.random() * 8);
  //show the integer rounded from 8 times the number generated by Math.random in console
  console.log(Math.floor(Math.random() * 8));
  //define variable holeL as a newly created div in the html file by the javascript
  var holeL = document.createElement('div');
  //attach a class called 'rec-b-top'to the element that is represented by variable holeL
  holeL.className = 'rec-b-top';
  //variable container is a element that has the id of container in the html file
  var container = document.getElementById('container');
  //attach the variable holeL to the container, so it will show up
  container.appendChild(holeL);
  //if the statement variable rand is smaller than 5 is true, pop up a window that shows text 'You have a leakage!'
  //and call function LateOri and function blueLeakLate
  //otherwise pop up a window that has the text of "Congratulation! Your water storage system is fine!"
  //and call the function OriWater
  if (rand < 5 == true) {
    alert('You have a leakage!')
    LateOri();
    blueLeakLate();
  }
  else {
    alert('Congratulation! Your water storage system is fine!')
    OriWater();
  }
}
//call the function aLeakage
aLeakage();

//interaction 4--only activated when one has a Leakage
//define a new variable called fixLeakage, get the element that has the id of 'r'
var fixLeakage=document.getElementById('r');
//make the element that is represented by variable fix leakage listen to a click, if clicked, do function 'Jokyfix'
fixLeakage.addEventListener('click',Jokyfix);
//create a function that is called Jokyfix
function Jokyfix(){
  //create a pop up window that shows up the span that contains "Don't worry, I will fix your leakage and you don't have to pay me 100 bucks."
  alert("Don't worry, I will fix your leakage and you don't have to pay me 100 bucks.");
  //define variable newRec as a newly created div by javascript in the html file
  var newRec=document.createElement('div');
  //add class 'rec-new' to the div that is representedby variable newRec
  newRec.classList='rec-new';
  //variable container is a element that has the id of container in the html file
  var container = document.getElementById('container');
  //attach the variable newRec to the container, so it will show up
  container.appendChild(newRec);
  //define variable newRecBlack as a new div that is created by javascript in the html file
  var newRecBlack=document.createElement('div');
  //add class 'rec-fix' to the div that is representedby variable newRecBlack
  newRecBlack.classList='rec-fix';
  //attach variable newRecBlack to the container variable so it shows up
  container.appendChild(newRecBlack);
}
